[package]
name = "natural-tts"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Creative Coders <officialccoders@gmail.com>"]
description = "High-level bindings to a variety of text-to-speech libraries."
homepage = "https://github.com/CodersCreative/natural-tts/tree/master"
readme = "README.md"
publish = true
keywords = ["text-to-speech", "coqui-ai", "gtts", "parler", "tts"]
categories = ["science", "api-bindings"]

[features]
tts-rs = []
coqui = []
parler = []
gtts = []
default = ["tts-rs", "coqui", "parler", "gtts"]

[dependencies]
derive_builder = { version = "0.20.0"}
hound = { version = "3.5.1"}
online = { version = "4.0.2"}
pyo3 = {version="0.21.2", features=["auto-initialize"]}
rodio = { version = "0.18.1"}
thiserror = { version = "1.0.61"}
tts = { version = "0.26.1"}
